# © 2026 aiaiaiai · aiaiaiai.org
# SPDX-License-Identifier: MIT

[package]
name = "h-ua-telegram"
description = "Telegram Bot API client for h-ua-bot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
h-ua-core = { path = "../h-ua-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
