# © 2026 aiaiaiai · aiaiaiai.org
# SPDX-License-Identifier: MIT

[package]
name = "h-ua-store"
description = "SQLite storage for h-ua-bot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
h-ua-core = { path = "../h-ua-core" }
rusqlite.workspace = true
